### ISSUE TITLE
SM has six grades

### ISSUE THREAD

**Issue by Golddouble** [open-spaced-repetition/fsrs-vs-sm15#2]
> There are five grades in SuperMemo, but only four grades in Anki. So I merged 1 and 2 in SuperMemo to 1 in Anki, and mapped 3, 4, and 5 in SuperMemo to 2, 3, and 4 in Anki.

Are you aware, that SM has 6 grades. 0-5 . But grade "0" is hidden since version 18. There is no more button. But we still can rate an Item with "0" with the key Ctrl+0.

**Comment by L-M-Sherlock** [comment]
OK. I will map 0 in SuperMemo to 1 in Anki.

**Comment by L-M-Sherlock** [comment]
@all-contributors please add @leee-z for data
