### ISSUE TITLE
[Question] Is the offline version ofFSRS in this repo different?

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs-vs-sm15#36]
I noticed that the difference in performance between FSRS offline and online is quite small. Moreover, FSRS offline performs quite poorly, compare to what we saw in [the benchmark](https://github.com/open-spaced-repetition/fsrs4anki/wiki/The-Benchmark).
That made me wonder: is the current version of FSRS, the one that is actually used in paractice, different from FSRS _offline_ in this repo?

**Comment by L-M-Sherlock** [comment]
I think the main difference is the data. SuperMemo doesn't have learning steps and relearning steps. So FSRS could performs will in SuperMemo dataset.

**Comment by L-M-Sherlock** [comment]
> Moreover, FSRS offline performs quite poorly, compare to what we saw in [the benchmark](https://github.com/open-spaced-repetition/fsrs4anki/wiki/The-Benchmark).

Which metrics are poorer than the benchmark?

**Comment by L-M-Sherlock** [comment]
I use 20 bins for calibration graph. How many bins did you use in the benchmark?

**Comment by Expertium** [comment]
https://colab.research.google.com/github/open-spaced-repetition/fsrs-vs-sm15/blob/main/compare.ipynb
https://colab.research.google.com/github/open-spaced-repetition/fsrs-vs-sm15/blob/main/compare_offline.ipynb
![image](https://github.com/open-spaced-repetition/fsrs-vs-sm15/assets/83031600/017bcd0b-fafd-475f-99e2-372fe2487e95)
RMSE and MAE are quite high. In my benchmark data (I believe I used 20 bins, yes) RMSE was below 7.7% in 90% of cases and MAE was below 5.3% in 90% of cases.
![image](https://github.com/open-spaced-repetition/fsrs-vs-sm15/assets/83031600/56fe14af-eff6-47f3-8bda-60e428c4c435)

**Comment by L-M-Sherlock** [comment]
My fault. I used 40 bins. It would increase the RMSE and MAE.

**Comment by L-M-Sherlock** [comment]
By the way, it is good news that the online version's performance approachs the offline version. Because I plan to implement the online version in Anki. The offline version only shows that ceiling of FSRS's capacity of fitting. It is trained in the evaluation data, so the evaluation result of offline version doesn't measure the model's generalization ability.

**Comment by Expertium** [comment]
What about a hybrid approach?
1. The user exports their collection to Google Colab/Hugging Face/rusn the optimizer locally (hopefully that will be available once the Rust implementation is completed), the optimal parameters are found using offline optimization.
2. The user pastes the optimal parameters into Anki
3. The optimal parameters are updated incrementall after each repetition

**Comment by L-M-Sherlock** [comment]
The experience replay has completed the work of offline version:

<img width="1025" alt="image" src="https://github.com/open-spaced-repetition/fsrs-vs-sm15/assets/32575846/fcff7be7-0297-4b44-824b-eca35e8ea3d8">

In the part of experience replay, all reviews are used to optimize the parameters. We can also split the reviews and increase the number of epoch there.

**Comment by L-M-Sherlock** [comment]
We can also allow user to triggle the experience replay manually.

**Comment by Expertium** [comment]
> We can also allow user to triggle the experience replay manually.

That's not a good idea. Most users will have no clue what it means and how to use it. I think that user should control only their retention and max. interval.

**Comment by L-M-Sherlock** [comment]
OK. Maybe we can set periods for experience replay. Per day/week/month/season or per hundred/thousand reviews.

**Comment by Expertium** [comment]
Now that I think about it, maybe you should add the option to enable FSRS both globally and for a specific deck individually (that deck will have it's own parameters).
I mean once FSRS is integrated into Anki.

**Comment by L-M-Sherlock** [comment]
Here is the design by dae: https://github.com/ankitects/anki/issues/2443#issuecomment-1683370494

**Comment by Expertium** [comment]
Yeah, but he doesn't specify whether users will be able to only have one set of parameters (global), or whether there will be an option have different sets for different decks.

**Comment by L-M-Sherlock** [comment]
I guess the parameters are bound to the deck options? Like `Daily Limits` and `Advanced`.

**Comment by L-M-Sherlock** [comment]
You can share your suggestion with dae in that issue.
