### ISSUE TITLE
[Feature Request] Modify the colab file to make it possible to run it on .txt files

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs-vs-sm15#5]
Currently, I have absolutely no idea whatsoever how to use https://colab.research.google.com/github/open-spaced-repetition/fsrs-vs-sm18/blob/main/compare.ipynb, aside from just looking at charts before running it.
I would like you to add a line of code similar to `filename = "collection-2022-09-18@13-21-58.colpkg"`, but for .txt files. Then other people will be able to use .txt files in this repository to run the comparison. Right now, even though you have provided the .txt files, there is no way to use them. If there is, then a guide is necessary.

**Comment by L-M-Sherlock** [comment]
Do you mean that we should provide an out-of-box notebook? It requires to combine convert.ipynb and compare.ipynb. But I prefer to collect data from users and run the experiments by myself. And I will record the results in README or WIKI.

**Comment by Expertium** [comment]
> It requires to combine convert.ipynb and compare.ipynb.

That would be ideal.

> And I will record the results in README or WIKI.

It would be nice if users could manually verify those results, but ok.
